mobileproject/mobileapp/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ntransactions
  devise_for :users
  resources :recurrent_transactions
  resources :customers
  resources :periods
  resources :categories
  get 'home/index'
  root "home#index"

end

mobileproject/mobileapp/app/controllers/ntransactions_controller.rb
class NtransactionsController < ApplicationController
  before_action :set_ntransaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /ntransactions
  # GET /ntransactions.json
  def index
    @ntransactions = Ntransaction.all
  end

  # GET /ntransactions/1
  # GET /ntransactions/1.json
  def show
  end

  # GET /ntransactions/new
  def new
    @ntransaction = Ntransaction.new
  end

  # GET /ntransactions/1/edit
  def edit
  end

  # POST /ntransactions
  # POST /ntransactions.json
  def create
    @ntransaction = Ntransaction.new(ntransaction_params)

    respond_to do |format|
      if @ntransaction.save
        format.html { redirect_to @ntransaction, notice: 'Ntransaction was successfully created.' }
        format.json { render :show, status: :created, location: @ntransaction }
      else
        format.html { render :new }
        format.json { render json: @ntransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ntransactions/1
  # PATCH/PUT /ntransactions/1.json
  def update
    respond_to do |format|
      if @ntransaction.update(ntransaction_params)
        format.html { redirect_to @ntransaction, notice: 'Ntransaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @ntransaction }
      else
        format.html { render :edit }
        format.json { render json: @ntransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ntransactions/1
  # DELETE /ntransactions/1.json
  def destroy
    @ntransaction.destroy
    respond_to do |format|
      format.html { redirect_to ntransactions_url, notice: 'Ntransaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ntransaction
      @ntransaction = Ntransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ntransaction_params
      params.require(:ntransaction).permit(:datetransaction, :transactiontype, :amount, :description, :category_id, :customer_id)
    end
end

mobileproject/mobileapp/app/helpers/ntransactions_helper.rb
module NtransactionsHelper
end

mobileproject/mobileapp/app/views/ntransactions/_form.html.erb
<%= simple_form_for @ntransaction, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :datetransaction %>
  <%= error_span(@ntransaction[:datetransaction]) %>
  <%= f.input :transactiontype %>
  <%= error_span(@ntransaction[:transactiontype]) %>
  <%= f.input :amount %>
  <%= error_span(@ntransaction[:amount]) %>
  <%= f.input :description %>
  <%= error_span(@ntransaction[:description]) %>
  <%= f.input :category_id %>
  <%= error_span(@ntransaction[:category_id]) %>
  <%= f.input :customer_id %>
  <%= error_span(@ntransaction[:customer_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ntransactions_path, :class => 'btn btn-default' %>
<% end %>

mobileproject/mobileapp/app/views/ntransactions/edit.html.erb
<%- model_class = Ntransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mobileproject/mobileapp/app/views/ntransactions/index.html.erb
<%- model_class = Ntransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:datetransaction) %></th>
      <th><%= model_class.human_attribute_name(:transactiontype) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ntransactions.each do |ntransaction| %>
      <tr>
        <td><%= link_to ntransaction.id, ntransaction_path(ntransaction) %></td>
        <td><%= ntransaction.datetransaction %></td>
        <td><%= ntransaction.transactiontype %></td>
        <td><%= ntransaction.amount %></td>
        <td><%= ntransaction.description %></td>
        <td><%= ntransaction.category_id %></td>
        <td><%= ntransaction.customer_id %></td>
        <td><%=l ntransaction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ntransaction_path(ntransaction), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ntransaction_path(ntransaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ntransaction_path,
            :class => 'btn btn-primary' %>

mobileproject/mobileapp/app/views/ntransactions/new.html.erb
<%- model_class = Ntransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mobileproject/mobileapp/app/views/ntransactions/show.html.erb
<%- model_class = Ntransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:datetransaction) %>:</strong></dt>
  <dd><%= @ntransaction.datetransaction %></dd>
  <dt><strong><%= model_class.human_attribute_name(:transactiontype) %>:</strong></dt>
  <dd><%= @ntransaction.transactiontype %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @ntransaction.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @ntransaction.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @ntransaction.category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @ntransaction.customer_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ntransactions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ntransaction_path(@ntransaction), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ntransaction_path(@ntransaction),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>