mobileproject/mobileapp/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ntransactions
  devise_for :users
  resources :recurrent_transactions
  resources :customers
  resources :periods
  resources :categories
  get 'home/index'
  root "home#index"

end

mobileproject/mobileapp/app/controllers/recurrent_transactions_controller.rb
class RecurrentTransactionsController < ApplicationController
  before_action :set_recurrent_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /recurrent_transactions
  # GET /recurrent_transactions.json
  def index
    @recurrent_transactions = RecurrentTransaction.all
  end

  # GET /recurrent_transactions/1
  # GET /recurrent_transactions/1.json
  def show
  end

  # GET /recurrent_transactions/new
  def new
    @recurrent_transaction = RecurrentTransaction.new
  end

  # GET /recurrent_transactions/1/edit
  def edit
  end

  # POST /recurrent_transactions
  # POST /recurrent_transactions.json
  def create
    @recurrent_transaction = RecurrentTransaction.new(recurrent_transaction_params)

    respond_to do |format|
      if @recurrent_transaction.save
        format.html { redirect_to @recurrent_transaction, notice: 'Recurrent transaction was successfully created.' }
        format.json { render :show, status: :created, location: @recurrent_transaction }
      else
        format.html { render :new }
        format.json { render json: @recurrent_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recurrent_transactions/1
  # PATCH/PUT /recurrent_transactions/1.json
  def update
    respond_to do |format|
      if @recurrent_transaction.update(recurrent_transaction_params)
        format.html { redirect_to @recurrent_transaction, notice: 'Recurrent transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @recurrent_transaction }
      else
        format.html { render :edit }
        format.json { render json: @recurrent_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recurrent_transactions/1
  # DELETE /recurrent_transactions/1.json
  def destroy
    @recurrent_transaction.destroy
    respond_to do |format|
      format.html { redirect_to recurrent_transactions_url, notice: 'Recurrent transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurrent_transaction
      @recurrent_transaction = RecurrentTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurrent_transaction_params
      params.require(:recurrent_transaction).permit(:startdate, :enddate, :period_id, :nextdate, :customer_id)
    end
end

mobileproject/mobileapp/app/helpers/recurrent_transactions_helper.rb
module RecurrentTransactionsHelper
end

mobileproject/mobileapp/app/views/recurrent_transactions/_form.html.erb
<%= simple_form_for @recurrent_transaction, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :startdate %>
  <%= error_span(@recurrent_transaction[:startdate]) %>
  <%= f.input :enddate %>
  <%= error_span(@recurrent_transaction[:enddate]) %>
  <%= f.association :period %>
  <%= error_span(@recurrent_transaction[:period]) %>
  <%= f.input :nextdate %>
  <%= error_span(@recurrent_transaction[:nextdate]) %>
  <%= f.association :customer %>
  <%= error_span(@recurrent_transaction[:customer]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recurrent_transactions_path, :class => 'btn btn-default' %>
<% end %>

mobileproject/mobileapp/app/views/recurrent_transactions/edit.html.erb
<%- model_class = RecurrentTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mobileproject/mobileapp/app/views/recurrent_transactions/index.html.erb
<%- model_class = RecurrentTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:startdate) %></th>
      <th><%= model_class.human_attribute_name(:enddate) %></th>
      <th><%= model_class.human_attribute_name(:period_id) %></th>
      <th><%= model_class.human_attribute_name(:nextdate) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recurrent_transactions.each do |recurrent_transaction| %>
      <tr>
        <td><%= link_to recurrent_transaction.id, recurrent_transaction_path(recurrent_transaction) %></td>
        <td><%= recurrent_transaction.startdate %></td>
        <td><%= recurrent_transaction.enddate %></td>
        <td><%= recurrent_transaction.period_id %></td>
        <td><%= recurrent_transaction.nextdate %></td>
        <td><%= recurrent_transaction.customer_id %></td>
        <td><%=l recurrent_transaction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recurrent_transaction_path(recurrent_transaction), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recurrent_transaction_path(recurrent_transaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recurrent_transaction_path,
            :class => 'btn btn-primary' %>

mobileproject/mobileapp/app/views/recurrent_transactions/new.html.erb
<%- model_class = RecurrentTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

mobileproject/mobileapp/app/views/recurrent_transactions/show.html.erb
<%- model_class = RecurrentTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:startdate) %>:</strong></dt>
  <dd><%= @recurrent_transaction.startdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enddate) %>:</strong></dt>
  <dd><%= @recurrent_transaction.enddate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:period_id) %>:</strong></dt>
  <dd><%= @recurrent_transaction.period_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nextdate) %>:</strong></dt>
  <dd><%= @recurrent_transaction.nextdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @recurrent_transaction.customer_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              recurrent_transactions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recurrent_transaction_path(@recurrent_transaction), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recurrent_transaction_path(@recurrent_transaction),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>